### ISSUE TITLE
Websocket support.

### ISSUE THREAD

**Issue by MrNoname3** [dani007200964/Commander-API#11]
**Is your feature request related to a problem? Please describe.**
While testing Shellminator's support for websocket, I noticed that the Commander API does not yet support websocket, so they are not compatible for now.

**Comment by dani007200964** [comment]
Yep, it was a problem, now I think it's gone. With 2b29ab072784767e0410ebd4fc076413165f2f79 I replaced my version of the response class with Arduino's builtin Stream class. There was a [request](https://github.com/dani007200964/Shellminator/issues/10) about it in the Shellminator library. Now it should work with almost anything in the Arduino environment. 

Please if you have some free time, test it, and share the results! 😃
