### ISSUE TITLE
Storing strings in flash on the Atmega/AVR platform 

### ISSUE THREAD

**Issue by MrNoname3** [dani007200964/Commander-API#8]
RAM usage is high on Atmega/AVR platforms, because the strings (used by the commander), are stored in the RAM istead of the flash.

**Comment by dani007200964** [comment]
I think I have a fix for it. I had to modify a lot in the original implementation. There is a chance that I screwed something up with it 😵‍💫. I tested it with ESP32, STM32F446RE, and Arduino Leonardo.

Please check this commit: 5f7c00a2aaf4dca028c183528b0a2e65ef873447 . It contains all the modifications for PROGMEM-enabled command data. Quickly I made an example for the progmem stuff: __Commander_simple_progmem.ino__

Sadly, the API_tree initialization process has to be separated into two-part for the PROGMEM version, but I think it is worth it on AVR devices.
